### PR TITLE
update CHANGELOG, fix cargo doc warnings and add missing documentation bits

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
cc @fluffysquirrels

After this PR lands I'll publish v0.2.0

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2ed242e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2ed242e2d0f3b1118c638e502c297b7e32ce6067 with merge 5c3e2b34cb3d02944be8d9625670892fdef76d1e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.16), [status-travis](https://travis-ci.org/japaric/itm/builds/327733383?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5c3e2b34cb3d02944be8d9625670892fdef76d1e to master...

**Comment by fluffysquirrels** [comment]
This looks great!

**Pull request merged**
