### PR TITLE
fallback to regular Files on Windows

### LINKED ISSUE #2: Windows support
This relies on named pipes (fifo files) to work. Is there an equivalent to that in Windows land?

### PR DESCRIPTION
**Pull request by japaric**
closes #2

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1602590 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1602590 with merge 1602590...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.1)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1602590 with merge 1602590...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/itm/builds/169110683)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 45021d4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 45021d4 with merge 45021d4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.2)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 45021d4 with merge 45021d4...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5ef2e87 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5ef2e87 with merge 5ef2e87...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.3), [status-travis](https://travis-ci.org/japaric/itm/builds/169118144)
Approved by: japaric
Pushing 5ef2e8770bede3df58c4945df5dded37baa82cb4 to master...

**Pull request merged**
