### PR TITLE
include git commit hash and date in version output (-V)

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ba33f3c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ba33f3c with merge ba33f3c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.4), [status-travis](https://travis-ci.org/japaric/itm/builds/169135944)
Approved by: japaric
Pushing ba33f3c3b9fee3270315e1a249471ac407a3e866 to master...

**Pull request merged**
