### PR TITLE
.travis: remove the webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2a27aa2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2a27aa2 with merge 2a27aa2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.5), [status-travis](https://travis-ci.org/japaric/itm/builds/174106831)
Approved by: japaric
Pushing 2a27aa2e2bd66598d39e5c1f8ec4f1a7987074b7 to master...

**Pull request merged**
