### PR TITLE
ci: switch to Trust v0.1.2

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2172d7a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2172d7abfe43b2cecb956ee89ee8313892ed357a with merge c3cc39a0eeceb9a0de1c9102020662b2e2394d98...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.9)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bec82f7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bec82f795d2b5a1a4e057bc29c6883e75889c0e7 with merge fd98b3619d8645eda006adeb4904a2e3bcef0328...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d17408 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d1740844eaf63e448685c89c976121a28cf18f7 with merge 7d06b4003eb4d90abc1195d9327697b8f8601c9e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/itm/build/1.0.12), [status-travis](https://travis-ci.org/japaric/itm/builds/320776696?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 7d06b4003eb4d90abc1195d9327697b8f8601c9e to master...

**Pull request merged**
