### PR TITLE
use libc::mkfifo instead of the external mkfifo command

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 46817b3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 46817b3 with merge 46817b3...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 93455e2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 93455e2 with merge 93455e2...

**Pull request merged**
